import React, { useState } from 'react'
import { getFormData } from '../utils/commonUtils'
import Head from 'next/head'
import Theaters from './components/theaters'
import styles from '../styles/Home.module.css'

function Home() {

    const [zipcode, setZipcode] = useState(null)
    const [isLoading, setIsLoading] = useState(false)
    const [theaters, setTheaters] = useState(null);

    const handleSubmit = (e) => {
        e.preventDefault();

        const formData = getFormData(e)

        if(formData && formData.formData && formData.formData.postalCode != '') {

            setIsLoading(true)
            
            const today = new Date();

            let bodyData = {
                date: today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate(),
                postalCode: formData.formData.postalCode
            }

            fetch("https://2oobz.com/api/index.php/nearByTheaterController/getFandorNearByTheaterData", {
                method: 'POST',
                body: JSON.stringify(bodyData),
                redirect: 'follow'
            })
            .then(response => response.json())
            .then(result => { 
                setTheaters(result.theaters) 
                setIsLoading(false)
            })
            .catch(error => console.log('error', error));
        }
    }

    const clearResult = () => {
        setTheaters(null)
        setZipcode(0)
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Ticket App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to Next Show Ticket App
                </h1>

                <form method='post' onSubmit={handleSubmit} noValidate>
                    <input value={zipcode} type='number' name='postalCode' placeholder='Enter Zipcode' />
                    <button type='submit'>Search</button>
                    <button type='button' onClick={clearResult}>clear</button>
                </form>

                <Theaters theaters={theaters} zipcode={zipcode}/>

                {isLoading && <p>Loading...</p>}
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://fandango.com"
                    target="_blank"
                    rel="fanndango"
                >
                    Powered by Fandango
                </a>
            </footer>
        </div>
    )
}

export default Home;